on:
  workflow_dispatch:
    inputs:
      url:
        description: 'url to scan'
        required: true
        default: ''
        
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: ${{ github.event.inputs.url }}
